version = 1

exclude_patterns = ["src/components/ui"]

# [[analyzers]]
# name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["vitest"]

[[transformers]]
name = "prettier"
