/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./src/components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    ArticleLayout1: typeof import('./src/components/ArticleLayout1.vue')['default']
    ArticleLayout2: typeof import('./src/components/ArticleLayout2.vue')['default']
    ArticleLayout3: typeof import('./src/components/ArticleLayout3.vue')['default']
    Avatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DevPanel: typeof import('./src/components/DevPanel.vue')['default']
    EmailForm: typeof import('./src/components/EmailForm.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LeakyPaywall: typeof import('./src/components/LeakyPaywall.vue')['default']
    Popover: typeof import('./src/components/ui/popover/Popover.vue')['default']
    PopoverContent: typeof import('./src/components/ui/popover/PopoverContent.vue')['default']
    PopoverTrigger: typeof import('./src/components/ui/popover/PopoverTrigger.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Sonner: typeof import('./src/components/ui/sonner/Sonner.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
    VisuallyHidden: typeof import('radix-vue')['VisuallyHidden']
  }
}
