on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

name: release
jobs:
  release-please:
    runs-on: [self-hosted]
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '20'
          cache: 'yarn'
      - uses: hashicorp/setup-terraform@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          terraform_version: '1.5.7'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: moonrepo/setup-toolchain@v0
        if: ${{ steps.release.outputs.release_created }}
      - name: deploy to CDN
        if: ${{ steps.release.outputs.release_created }}
        run: moon ci :deploy
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
