name: Unit Test Coverage Baseline

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    name: Baseline Unit Test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: moonrepo/setup-toolchain@v0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Cache Moonrepo
        uses: actions/cache@v4
        with:
          path: |
            .moon/cache/hashes
            .moon/cache/outputs
          key: cache-moon-${{ github.sha }}
          restore-keys: |
            cache-moon-
      - run: moon run :test-coverage
      - run: moon ci :build
      - uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cp ./coverage/lcov.info ./coverage/base.info
      - uses: actions/cache/save@v4
        with:
          path: |
            ./coverage/base.info
          key: base-coverage-${{ github.run_id }}
